# Site settings
title: "Math Summaries"
description: "Summaries of various math topics"
baseurl: "" # Leave blank for user.github.io or set to "/repository-name" for project pages
url: "https://yeahBOYYYYY.github.io" # Replace with your GitHub Pages URL

# Build settings
source: website/version2 # Points to where the Jekyll files are
permalink: /index.html # Set homepage to index.html in version2 directory

# Jekyll settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
